# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ipc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RiskState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RiskState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRiskState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RiskState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RiskState
    def Signals(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from statarb.ipc.Signal import Signal
            obj = Signal()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RiskState
    def SignalsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RiskState
    def SignalsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # RiskState
    def SequenceNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RiskState
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def RiskStateStart(builder):
    builder.StartObject(3)

def Start(builder):
    RiskStateStart(builder)

def RiskStateAddSignals(builder, signals):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(signals), 0)

def AddSignals(builder, signals):
    RiskStateAddSignals(builder, signals)

def RiskStateStartSignalsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSignalsVector(builder, numElems):
    return RiskStateStartSignalsVector(builder, numElems)

def RiskStateAddSequenceNumber(builder, sequenceNumber):
    builder.PrependUint64Slot(1, sequenceNumber, 0)

def AddSequenceNumber(builder, sequenceNumber):
    RiskStateAddSequenceNumber(builder, sequenceNumber)

def RiskStateAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(2, timestamp, 0)

def AddTimestamp(builder, timestamp):
    RiskStateAddTimestamp(builder, timestamp)

def RiskStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return RiskStateEnd(builder)
