# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ipc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Signal(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Signal()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSignal(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Signal
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Signal
    def TargetSymbol(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Signal
    def HedgeSymbol(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Signal
    def HedgeRatio(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Signal
    def Threshold(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def SignalStart(builder):
    builder.StartObject(4)

def Start(builder):
    SignalStart(builder)

def SignalAddTargetSymbol(builder, targetSymbol):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(targetSymbol), 0)

def AddTargetSymbol(builder, targetSymbol):
    SignalAddTargetSymbol(builder, targetSymbol)

def SignalAddHedgeSymbol(builder, hedgeSymbol):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(hedgeSymbol), 0)

def AddHedgeSymbol(builder, hedgeSymbol):
    SignalAddHedgeSymbol(builder, hedgeSymbol)

def SignalAddHedgeRatio(builder, hedgeRatio):
    builder.PrependFloat64Slot(2, hedgeRatio, 0.0)

def AddHedgeRatio(builder, hedgeRatio):
    SignalAddHedgeRatio(builder, hedgeRatio)

def SignalAddThreshold(builder, threshold):
    builder.PrependFloat64Slot(3, threshold, 0.0)

def AddThreshold(builder, threshold):
    SignalAddThreshold(builder, threshold)

def SignalEnd(builder):
    return builder.EndObject()

def End(builder):
    return SignalEnd(builder)
